version: '3.8'

services:
  database:
    image: tseniukh/springtask-compose
    environment:
      MYSQL_DATABASE: hometaskspring
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3307"
    volumes:
      - my-db:/var/lib/mysql
  bootdocker:
    depends_on:
      - database
    image: tseniukh/springtask-compose
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3307/hometaskspring
    volumes:
      - /data/bootdocker
    stdin_open: true
    tty: true
